config/routes.rb
MachineshopPortal::Application.routes.draw do

  resources :styles
  resources :faqs
  resources :white_papers
  resources :example_applications

  get "welcomes/index"
  root(:to => 'welcomes#index')

  resource :dashboard do
    collection do
      get 'index'
      get 'api_usage'
      get 'get_device_instance_last_report'
      get 'get_device_instances'
      get 'get_device_instances_summary'
      get 'get_device_instance_report_count'
      get 'save_widgets_state'
      get 'system_usage'
      get 'retrieve_users'
      get 'retrieve_user_by_id'
      get 'retrieve_rules'
      get 'retrieve_rule_by_id'
      get 'retrieve_custom_apis'
    end
  end

  resource :widget do
    collection do
      get 'get_device_instance_last_report'
      get 'get_device_instances'
      get 'get_device_instances_summary'
      get 'get_device_instance_report_count'
      get 'retrieve_users'
      get 'retrieve_user_by_id'
      get 'retrieve_customers'
      get 'retrieve_customer_by_id'
      get 'retrieve_rules'
      get 'retrieve_rule_by_id'
      get 'retrieve_custom_apis'
      get 'retrieve_custom_api_by_id'
    end
  end

  get "admin/show"

  get "documents/index"

  get "documents/provider_docs", controller: 'documents', action: 'provider_docs', as: 'provider_docs'

  get "documents/show"

  get "reports/index"

  get "reports/show"

  get "resources/api_documentation"

  get "resources/ideas_examples"

  get "users/new_api_key/:id", controller: 'users', action: 'new_api_key', as: 'new_api_key'

  resource :user_session, only: [:new, :create, :destroy]
  resource :rules
  resources :custom_apis, :documents, :users, :customers, :resources, :support_tickets
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :question
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_filter :require_signed_in_user
  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq = Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.json
  def new
    if current_user.admin?
      @faq = Faq.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @faq }
      end
    else
      redirect_to faqs_url
    end
  end

  # GET /faqs/1/edit
  def edit
    if current_user.admin?
      @faq = Faq.find(params[:id])
    else
      redirect_to faqs_url
    end
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(params[:faq])

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render json: @faq, status: :created, location: @faq }
      else
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(params[:faq])
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy
    render nothing: true

    # respond_to do |format|
    #   format.html { redirect_to faqs_url }
    #   format.json { head :no_content }
    # end
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.haml
= form_for @faq do |f|
  .span12
    .error
      - if @faq.errors.any?
        #error_explanation
          %p.ms-red-text= "#{pluralize(@faq.errors.count, "error")} prohibited this faq from being saved:"
          %ul
            - @faq.errors.full_messages.each do |msg|
              %li.ms-red-text= msg

  .row-fluid.span12
    .span2
      .form_label
        = f.label :question
    .span10
      .form_field
        = f.text_area :question, rows: '3', class: 'input-block-level'
  .row-fluid.span12
    .span2
      .form_label
        = f.label :answer
    .span10
      .form_field
        = f.text_area :answer, rows: '12', class: 'input-block-level'

  .row-fluid.span12
    #save-cancel
      = link_to 'Cancel', faqs_path
      = f.submit 'Save', class: 'btn-large btn-custom-large'

app/views/faqs/edit.html.haml
.span10#edit-faq-wrap
  .row-fluid
    %h3.span5 Edit FAQ

  .row-fluid.no-margin-left.dashed-border
    .span11
      = render 'form'

app/views/faqs/index.html.haml
.span10#faq-index-wrapper
  .span12.row-fluid
    %h3.span5 FAQ

  .span12.table-it.no-margin-left
    %p.span10.no-margin-left View frequently asked questions.
    - if current_user.admin?
      .span2
        %ul.add-record#add-faq
          %li= link_to image_tag('add-btn.png'), new_faq_path
          %li= link_to "Add", new_faq_path

  - @faqs.each do |faq|
    .span12.no-margin-left.faq-listing
      .span12.no-margin-left.dashed-border
        .span10
          %h5.faq-question= faq.question
          .reveal-btn{data: {id: faq.id}}
        - if current_user.admin?
          .span2#edit-delete-faq
            = link_to("Edit", edit_faq_path(faq.id))
            = link_to("/ Delete", faq_path(faq.id), class: "delete-faq", confirm: "Delete question and answer for: '#{faq.question}'?", method: :delete, remote: true)
      .span12.no-margin-left.faq-answer{ id: "faq-answer-#{faq.id}"}
        %p= faq.answer

app/views/faqs/new.html.haml
.span10#new-faq-wrap
  .row-fluid
    %h3.span5 New FAQ

  .row-fluid.no-margin-left.dashed-border
    .span11
      = render 'form'

app/views/faqs/show.html.haml
%p#notice= notice

%p
  %b Question:
  = @faq.question
%p
  %b Answer:
  = @faq.answer

= link_to 'Edit', edit_faq_path(@faq)
\|
= link_to 'Back', faqs_path