config/routes.rb
MachineshopPortal::Application.routes.draw do

  resources :styles
  resources :faqs
  resources :white_papers
  resources :example_applications

  get "welcomes/index"
  root(:to => 'welcomes#index')

  resource :dashboard do
    collection do
      get 'index'
      get 'api_usage'
      get 'get_device_instance_last_report'
      get 'get_device_instances'
      get 'get_device_instances_summary'
      get 'get_device_instance_report_count'
      get 'save_widgets_state'
      get 'system_usage'
      get 'retrieve_users'
      get 'retrieve_user_by_id'
      get 'retrieve_rules'
      get 'retrieve_rule_by_id'
      get 'retrieve_custom_apis'
    end
  end

  resource :widget do
    collection do
      get 'get_device_instance_last_report'
      get 'get_device_instances'
      get 'get_device_instances_summary'
      get 'get_device_instance_report_count'
      get 'retrieve_users'
      get 'retrieve_user_by_id'
      get 'retrieve_customers'
      get 'retrieve_customer_by_id'
      get 'retrieve_rules'
      get 'retrieve_rule_by_id'
      get 'retrieve_custom_apis'
      get 'retrieve_custom_api_by_id'
    end
  end

  get "admin/show"

  get "documents/index"

  get "documents/provider_docs", controller: 'documents', action: 'provider_docs', as: 'provider_docs'

  get "documents/show"

  get "reports/index"

  get "reports/show"

  get "resources/api_documentation"

  get "resources/ideas_examples"

  get "users/new_api_key/:id", controller: 'users', action: 'new_api_key', as: 'new_api_key'

  resource :user_session, only: [:new, :create, :destroy]
  resource :rules
  resources :custom_apis, :documents, :users, :customers, :resources, :support_tickets
end

app/views/shared/_footer.html.haml
%footer
  - if params[:controller] != 'user_sessions'
    .row-fluid.footer
      .navbar
        %a.btn.btn-navbar(data-target="#footer-nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .nav-collapse#footer-nav-collapse
          .span2
          .span2
            %ul
              %li= link_to "HOME", "/"
              %li= link_to "DASHBOARD", dashboard_path
              %li= link_to "ADMIN", users_url
              %li= link_to "DOCUMENTS", documents_index_url
          .span2
            %ul
              %li= link_to "ADD NEW WIDGET", "#"
              %li= link_to "HELP?", "#"
              %li= link_to "LOGOUT", user_session_path, method: :delete
          .span3
            %ul
              %li= link_to "PARTNERSHIPS, SALES AND GENERAL INQUIRIES", "#"
              %li= link_to "CONNECT@MACHINESHOP.IO", "#"
              %li= link_to "TECHSUPPORT SUPPORT@MACHINESHOP.IO", "#"
              %li= link_to "TEL. +1 781 580 4625", "#"
          .span3
            %div#social-icons
              = image_tag "social_icon_in.png", id: "linked-in"
              = image_tag "social_icon_twitter.png",  id: "twitter"
            %p#copyright
              \&copy;2012
              %span Machineshop
              \&ndash; All rights reserved
  - if params[:controller] == 'user_sessions'
    .row-fluid.footer
      .navbar
        %a.btn.btn-navbar(data-target="#footer-nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .nav-collapse#footer-nav-collapse
          .span2
          .span4
            %ul
              %li= link_to "PARTNERSHIPS, SALES AND GENERAL INQUIRIES", "#"
              %li= link_to "CONNECT@MACHINESHOP.IO", "#"
              %li= link_to "TECHSUPPORT SUPPORT@MACHINESHOP.IO", "#"
              %li= link_to "TEL. +1 781 580 4625", "#"
          .span3
          .span3
            %div#social-icons
              = image_tag "social_icon_in.png", id: "linked-in"
              = image_tag "social_icon_twitter.png",  id: "twitter"
            %p#copyright
              \&copy;2012
              %span Machineshop
              \&ndash; All rights reserved

app/views/shared/_global_sidebar_nav.html.haml
#global-sidebar
  %ul.nav.nav-list#icon-links
    %li
      - if controller?(['documents'])
        = image_tag('tools-small.png', class: "active-img")
      - else
        = link_to image_tag('tools-small.png'), documents_path
    %li
      - if controller?(%w(resources support_tickets white_papers faqs))
        = image_tag('doc-small.png', class: "active-img")
      - else
        = link_to image_tag('doc-small.png'), resources_path
    %li
      - if current_user.admin?
        - if controller?(['users', 'styles'])
          = image_tag('gear-small.png', class: "active-img")
        - else
          = link_to image_tag('gear-small.png'), edit_user_path(current_user._id)
      - elsif current_user.role == 'publisher'
        - if controller?(%w(customers users custom_apis styles))
          = image_tag('gear-small.png', class: "active-img")
        - else
          = link_to image_tag('gear-small.png'), edit_user_path(current_user._id)
      - else current_user.role == 'consumer'
        - if controller?(['users', 'styles'])
          = image_tag('gear-small.png', class: "active-img")
        - else
          = link_to image_tag('gear-small.png'), edit_user_path(current_user._id)

    %li
      - if controller?(['reports'])
        = image_tag('barchart-small.png', class: "active-img")
      - else
        = link_to image_tag('barchart-small.png'), reports_index_path
    %li
      - if controller?(['dashboards'])
        = image_tag('toolbox-small.png', class: "active-img")
      - else
        = link_to image_tag('toolbox-small.png'), dashboard_path

app/views/shared/_header_buttons.haml
%li.pull-right.collapse-widget{ :style => collapsed ? 'display: none;' : 'display: block;' }
  &minus;
%li.pull-right.expand-widget{ :style => collapsed ? 'display: block;' : 'display: none;' }
  +
%li.pull-right.close_icon= image_tag 'delete_small.png'
%li.pull-right.sync_icon= image_tag 'sync_small.png'

app/views/shared/_navigation.html.haml
- if controller?(['user_sessions'])
  .row-fluid#login-nav
    .span6
      = image_tag 'logo-dark.png'

- else
  .row-fluid.logo-row
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner#top-nav
        .container-fluid
          %a.btn.btn-navbar(data-target="#top-nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %ul#logo-greet
            %li#logo
              - if current_user.logo_url.blank?
                = link_to image_tag('logo.png'), welcomes_index_path
              - else
                = link_to image_tag("#{current_user.logo_url}", id: 'customer-logo'), welcomes_index_path
            %li#greeting
              - if current_user.present?
                = "Welcome #{current_user.full_name}"
              - else
                = "Welcome"
          .nav-collapse.clearfix#top-nav-collapse
            %ul#top-nav-list
              %li#help
                = link_to "Help", resources_path
              - if current_user.present?
                %li
                  = link_to 'My Settings', edit_user_path(current_user)
              - if current_user.present?
                %li#login-out
                  = link_to "Logout", user_session_path, method: :delete
              - else !current_user.present? and controller?(['user_sessions'])
                %li#login-out
                  = link_to "Login", new_user_session_path
              %li
                = form_tag(documents_index_path, :method => :get) do
                  = text_field_tag 'search_string', nil, :placeholder => "Search", id: 'nav-search-box'
                  = submit_tag "Search", :class => "btn btn-mini"

app/views/shared/_pager.haml
#paginate-holder.pager{'data-page' => '1'}
  %a.previous.disabled
    < Prev
  %span.current_page
    1
  %a.next.disabled
    Next >

app/views/shared/_reports_sidebar.html.haml
%h4 Reports &amp; Analytics
%p Helpful reports and analytics to determine application performance.
%ul.nav.nav-list

app/views/shared/_resources_sidebar.html.haml
%h4 Resources
%p Get help here with issues and questions.
%ul.nav.nav-list
  - if (controller?(['resources']) && controller.action_name == 'index') or controller?(['support_tickets'])
    %li.active-side-nav
      = link_to 'Support', resources_path
    %ul.nav.nav-list.sub-nav
      - if controller?(['support_tickets']) && controller.action_name == 'new'
        %li.active-sub-nav/
      - else
        %li/
      = link_to 'Submit Ticket', new_support_ticket_path
      - if controller?(['support_tickets']) && controller.action_name == 'index'
        %li.active-sub-nav/
      - else
        %li/
      = link_to 'Existing Tickets', support_tickets_path
      %li= link_to 'FAQ', faqs_path
  - else
    %li
      = link_to 'Support', resources_path

  - if (controller?(['resources']) && controller.action_name == 'ideas_examples') or controller?(['white_papers', 'faqs', 'example_applications'])
    %li.active-side-nav
      = link_to 'Ideas & Examples', resources_ideas_examples_path
    %ul.nav.nav-list.sub-nav
      - if controller?(['faqs'])
        %li.active-sub-nav/
      - else
        %li/
      = link_to 'FAQ', faqs_path
      - if controller?(['white_papers'])
        %li.active-sub-nav/
      - else
        %li/
      = link_to 'Getting Started & White Papers', white_papers_path
      - if controller?(['example_applications'])
        %li.active-sub-nav/
      - else
        %li/
      = link_to 'Example Applications', example_applications_path
  - else
    %li
      = link_to 'Ideas & Examples', resources_ideas_examples_path

  - if (controller?(['resources']) && controller.action_name == 'api_documentation')
    %li.active-side-nav/
  - else
    %li/
  = link_to 'API Documentation', resources_api_documentation_path

app/views/shared/_services_sidebar.html.haml
#services-sidebar
  %h4 Services
  %p All the information you need to utilize our API services in your application.
  - if @search_results
    %div{id: "#{@search_results}"}
      %h4 Search Results
      = link_to 'All Docs', documents_path, id: 'close-search'
      %ul.nav.nav-list
        - @document_categories.each do |category_name, documents|
          %li
            %a.category-name= category_name
  - else
    %ul.nav.nav-list#services
      - @category_names.each do |category_name|
        %li
          %a{ class: "category-name", name: category_name }= category_name

app/views/shared/_sidebar_nav.html.haml
- if !controller?(%w(dashboards welcomes))
  .sidebar-nav#variable-sidebar
    - if controller?(['documents'])
      = render 'shared/services_sidebar'
    - elsif controller?(%w(resources support_tickets white_papers faqs example_applications))
      = render 'shared/resources_sidebar'
    -elsif controller?(['reports'])
      = render 'shared/reports_sidebar'

    - elsif controller?(%w(users customers custom_apis styles))
      - if current_user.role == 'admin'
        %h4 Admin
        %p Configure your account and manage your users and their access to the services.
      - elsif current_user.role == 'publisher'
        %h4 Manage
        %p Configure your account and manage your customers and their access to the services.
      - else current_user.role == 'consumer'
        %h4 My Settings
        %p Manage your account and check on your service settings.

      %ul.nav.nav-list
        - if current_user.role == 'admin'
          - if controller?(['users']) && params[:id] == current_user.id
            %li.active-side-nav/
          - else
            %li/
          = link_to 'My Settings', edit_user_path(current_user._id)

          - if controller?(['users']) && params[:id] != current_user.id
            %li.active-side-nav/
          - else
            %li/
          = link_to 'Manage Users', users_url

          - if controller?(['styles'])
            %li.active-side-nav/
          - else
            %li/
          = link_to "Custom UI", styles_path

        - if current_user.role == 'publisher'
          - if controller?(['users']) && params[:id] == current_user.id
            %li.active-side-nav/
          - else
            %li/
          = link_to 'My Settings', edit_user_path(current_user._id)

          - if controller?(['customers']) or (controller?(['users']) && params[:id] != current_user.id)
            %li.active-side-nav/
          - else
            %li/
          = link_to 'Manage Customers', customers_path

          - if controller?(['custom_apis'])
            %li.active-side-nav/
          - else
            %li/
          = link_to "Custom API's", custom_apis_path

          - if controller?(['styles'])
            %li.active-side-nav/
          - else
            %li/
          = link_to "Custom UI", new_style_path