config/routes.rb
MachineshopPortal::Application.routes.draw do

  resources :styles
  resources :faqs
  resources :white_papers
  resources :example_applications

  get "welcomes/index"
  root(:to => 'welcomes#index')

  resource :dashboard do
    collection do
      get 'index'
      get 'api_usage'
      get 'get_device_instance_last_report'
      get 'get_device_instances'
      get 'get_device_instances_summary'
      get 'get_device_instance_report_count'
      get 'save_widgets_state'
      get 'system_usage'
      get 'retrieve_users'
      get 'retrieve_user_by_id'
      get 'retrieve_rules'
      get 'retrieve_rule_by_id'
      get 'retrieve_custom_apis'
    end
  end

  resource :widget do
    collection do
      get 'get_device_instance_last_report'
      get 'get_device_instances'
      get 'get_device_instances_summary'
      get 'get_device_instance_report_count'
      get 'retrieve_users'
      get 'retrieve_user_by_id'
      get 'retrieve_customers'
      get 'retrieve_customer_by_id'
      get 'retrieve_rules'
      get 'retrieve_rule_by_id'
      get 'retrieve_custom_apis'
      get 'retrieve_custom_api_by_id'
    end
  end

  get "admin/show"

  get "documents/index"

  get "documents/provider_docs", controller: 'documents', action: 'provider_docs', as: 'provider_docs'

  get "documents/show"

  get "reports/index"

  get "reports/show"

  get "resources/api_documentation"

  get "resources/ideas_examples"

  get "users/new_api_key/:id", controller: 'users', action: 'new_api_key', as: 'new_api_key'

  resource :user_session, only: [:new, :create, :destroy]
  resource :rules
  resources :custom_apis, :documents, :users, :customers, :resources, :support_tickets
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  attr_accessible :name, :default_column

  has_many :user_widgets
  has_many :widget_permissions
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  include ApplicationHelper

  before_filter :require_signed_in_user

  def get_device_instance_last_report
    page = params[:page] ? params[:page] : 1
    device = find_device_instance(params[:device_id], page)
    last_report = DeviceInstance.last_reports(current_user,[params[:device_id]])#device.last_report(current_user)
    last_report = last_report[params[:device_id]]
    time = last_report ? format_time(last_report.created_at) : "(no reports)"
    render :partial => 'shared/widgets/last_report', :locals => {time: time, di: device, report: last_report}
  end

  def get_device_instances_last_reports
    page = params[:page] ? params[:page] : 1
    last_reports = params[:device_instance_ids] ? DeviceInstance.last_reports(current_user,params[:device_instance_ids]) : nil
    params[:device_instance_ids].each do |id|
      last_reports[id] ? last_reports[id].created_at = format_time(last_reports[id].created_at) : last_reports[id] = nil
    end
    render :partial => 'shared/widgets/last_reports', :locals => {last_reports: last_reports, page: page}
  end

  def get_device_instances
    page = params[:page] ? params[:page] : 1
    render :partial => 'shared/widgets/device_instances_last_report', :locals => {device_instances: device_instances(page)}
  end

  def get_device_instances_summary
    page = params[:page] ? params[:page] : 1
    render :partial => 'shared/widgets/device_instances_report_count', :locals => {device_instances: device_instances(page)}
  end

  def get_device_instance_report_count
    page = params[:page] ? params[:page] : 1
    device = find_device_instance(params[:device_id], page)
    count_object = [device._id, device.name, device.total_reports(current_user)[:count]]
    render :partial => 'shared/widgets/report_count', :locals => {device_instance_count: count_object, device_instance: device}
  end

  def api_usage
    render json: [400, 300, 200, 500, 600, 500, 100, 300, 800, 900, 300, 500, 700]
  end

  def system_usage
    render json: [700, 800, 200, 500, 600, 100, 800, 700, 200, 100, 600, 700, 700]
  end

  def retrieve_users
    page = params[:page] ? params[:page] : 1
    query = params[:query] ? params[:query] : nil
    users_array = users(query, page)
    respond_to do |format|
      format.html { render :partial => 'shared/widgets/user_list', :locals => {users: users_array} }
      format.json { render json: users_array }
    end
  end

  def retrieve_user_by_id
    user = find_user(params[:user_id], params[:page], params[:query])
    render :partial => 'shared/widgets/user_row', :locals => {user_instance: user}
  end

  def retrieve_customers
    page = params[:page] ? params[:page] : 1
    query = params[:query] ? params[:query] : nil
    customers_array = customers(query, page)
    respond_to do |format|
      format.html { render :partial => 'shared/widgets/customer_list', :locals => {customers: customers_array} }
      format.json { render json: customers_array }
    end
  end

  def retrieve_customer_by_id
    customer = find_customer(params[:user_id], params[:page], params[:query])
    render :partial => 'shared/widgets/customer_row', :locals => {customer_instance: customer}
  end

  def retrieve_rules
    page = params[:page] ? params[:page] : 1
    query = params[:query] ? params[:query] : nil
    rules_array = rules(query, page)
    respond_to do |format|
      format.html { render :partial => 'shared/widgets/rule_list', :locals => {rules: rules_array} }
      format.json { render json: rules_array }
    end
  end

  def retrieve_rule_by_id
    rule = find_rule(params[:rule_id], params[:page], params[:query])
    render :partial => 'shared/widgets/rule_row', :locals => {rule_instance: rule}
  end

  def retrieve_custom_apis
    page = params[:page] ? params[:page] : 1
    query = params[:query] ? params[:query] : nil
    custom_apis_array = custom_apis(query, page)
    respond_to do |format|
      format.html { render :partial => 'shared/widgets/custom_api_list', :locals => {custom_apis: custom_apis_array} }
      format.json { render json: custom_apis_array }
    end
  end

  def retrieve_custom_api_by_id
    custom_api = find_custom_api(params[:custom_api_id], params[:page], params[:query])
    render :partial => 'shared/widgets/custom_api_row', :locals => {custom_api_instance: custom_api}
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/shared/widgets/_api_usage.html.haml
%ul.machineshop-header
  %li= image_tag 'bar_chart_small.png'
  %li API USAGE LAST 30 DAYS
  = render partial: 'shared/header_buttons', locals: {collapsed: collapsed}
.machineshop-inner-container{ :style => collapsed ? 'display: none;' : '' }
  %div#api-chart
  .table_container
    %table.table.table-striped#api-usage-data
      %thead
        %tr
          %th API Name
          %th Call Count
      %tbody
        %tr
          %td GET /user
          %td 2345
        %tr
          %td GET /report
          %td 2345
        %tr
          %td GET /role
          %td 2345
        %tr
          %td GET /google/geocode
          %td 2345

app/views/shared/widgets/_custom_api_list.html.haml
- if custom_apis && custom_apis.length > 0
  - custom_apis.each do |ca|
    %tr.custom_api_info{'data-custom-api_id' => ca._id}
      %td.loading
      %td
        = ca.base_domain
      %td
      %td
      %td
- else
  %tr.custom_api_info
    %td
    %td
      (no results)
    %td
    %td
    %td

app/views/shared/widgets/_customer_list.haml
- if customers && customers.length > 0
  - customers.each do |u|
    %tr.customer_info{'data-customer_id' => u._id}
      %td.loading
      %td
        = u.email
      %td
      %td
      %td
- else
  %tr.customer_info
    %td
    %td
      (no results)
    %td
    %td
    %td

app/views/shared/widgets/_customer_management.haml
- if controller?(['dashboards'])
  %ul.machineshop-header
    %li= image_tag'users_small.png'
    %li CUSTOMER MANAGEMENT
    = render partial: 'shared/header_buttons', locals: {collapsed: collapsed}
  .machineshop-inner-container.customer_management{ :style => collapsed ? 'display: none;' : '' }
    = form_tag('/widgets/retrieve_users', :method => :get, :id => 'user_search') do
      = text_field_tag :query, nil, :placeholder => "Search Customers", :id => 'customer-search-box'
      = submit_tag "Search", :class => "btn btn-mini"
    %ul.add-record#add-customer
      %li= link_to image_tag('add-btn.png'), new_user_path
      %li= link_to "Add", new_user_path

    .table_container
      %table.table.table-striped#customer-management-data
        %thead
          %tr
            %th Name
            %th Email
            %th Role
            %th Company
            %th Actions
        %tbody.paged_data
          %tr
            %td.loading
            %td
              Loading...
            %td
            %td
            %td

  .row-fluid.no-margin-left
    = render 'shared/pager'

- else
  .row-fluid
    %table.table.table-bordered.table-striped#customer-management-data
      %thead
        %tr
          %th NAME
          %th EMAIL
          %th ROLE
          %th COMPANY
          %th ACTIONS
      %tbody.paged_data
        %tr
          %td.loading
          %td
            Loading...
          %td
          %td
          %td

  .row-fluid.no-margin-left
    = render 'shared/pager'

app/views/shared/widgets/_customer_row.haml
%td
  = customer_instance.full_name
%td
  %a{:href => "mailto:#{customer_instance.email}"}
    = customer_instance.email.truncate(24)
%td
  = customer_instance.role.humanize
%td
  = customer_instance.company_name.truncate(24)
%td
  %span
    = link_to("Edit", edit_customer_path(customer_instance._id))
  - if customer_instance._id != current_user.id
    %span
    = link_to "/ Delete", customer_path(customer_instance._id),
    class: "delete",
    confirm: "Delete '#{customer_instance.full_name}'?",
    method: :delete,
    remote: true
    :javascript
      $("a.delete").bind("ajax:success", function(evt, data, status, xhr) {
      $(this).closest("tr").fadeOut(500);
      });
      $("a.delete").bind("ajax:error", function(evt, xhr, status, error) {
      alert("We're sorry but something went wrong. The user was not deleted.")
      });

app/views/shared/widgets/_last_device_report.html.haml
%ul.machineshop-header
  %li= image_tag 'computer_small.png'
  %li LAST DEVICE REPORT DATA
  = render partial: 'shared/header_buttons', locals: {collapsed: collapsed}
.machineshop-inner-container.device_instances_reports{ :style => collapsed ? 'display: none;' : '' }
  .table_container
    %table.table.table-striped#device-report-data
      %thead
        %tr
          %th Date/Time
          %th Device Name
          %th Device Type
          %th Last Message
      %tbody.paged_data
        %tr
          %td.loading
          %td
            Loading...
          %td
          %td

  = render 'shared/pager'

#report_detail.modal.hide.fade{:style => "display: none;"}
  .modal-header
    %a.close{'data-dismiss'=>"modal"}
    %h3 Report Detail

  .modal-body{:style => "height: 350px; overflow-y: scroll;"}
    %p.modal_report_details
  .modal-footer
    %a.btn{:href=>"#", 'data-dismiss'=>"modal"}
      Close

app/views/shared/widgets/_last_report.haml
%td
  = time
%td
  = di.name
%td
  = di.device[:model]
%td
  - if report
    .btn.btn-mini.btn-custom-msg
      %a{:href => "#report_detail", 'data-reportid' => report._id, 'data-toggle' => 'modal', :onclick => "javascript:$('.modal_report_details').html('#{display_json(report.payload)}')"}
        Message Detail
  - else
    (no details)

app/views/shared/widgets/_last_reports.haml
- last_reports.each do |id, report|
  - di = find_device_instance(id, page)
  %td.local-time
    = format_time(report.created_at)
  %td
    = di.name
  %td
    = di.device[:model]
  %td
    - if report
      .btn.btn-mini.btn-custom-msg
        %a{:href => "#report_detail", 'data-reportid' => report._id, 'data-toggle' => 'modal', :onclick => "javascript:$('.modal_report_details').text('#{report.payload.to_json}')"
          Message Detail
    - else
      (no details)

  

app/views/shared/widgets/_rule_list.html.haml
- if rules && rules.length > 0
  - rules.each do |r|
    %tr.rule_info{'data-rule_id' => r._id}
      %td.loading
      %td
        = r.description
      %td
- else
  %tr.rule_info
    %td
      (no results)
    %td
    %td

app/views/shared/widgets/_rule_management.html.haml
%ul.machineshop-header
  %li= image_tag 'rulers2.png', { style: "height:32px; width:32px" }
  %li RULE MANAGEMENT
  = render partial: 'shared/header_buttons', locals: {collapsed: collapsed}
.machineshop-inner-container.rule_management{ :style => collapsed ? 'display: none;' : '' }
  .table_container
    /%ul#new-rule.add-record
    /%li
    /= link_to image_tag('add-btn.png'), new_rules_path
    /%li
    /= link_to "Add", new_rules_path
    .row-fluid
      %table.table.table-striped#rule-management-data
        %thead
          %tr
            %th Description
            %th Date Created
            %th Delete
        %tbody.paged_data
          %tr
            %td.loading
            %td
              Loading...
            %td

  = render 'shared/pager'

app/views/shared/widgets/_system_status.html.haml
%ul.machineshop-header
  %li= image_tag 'battery_small.png'
  %li SYSTEM STATUS
  = render partial: 'shared/header_buttons', locals: {collapsed: collapsed}
.machineshop-inner-container#system-status-data{ :style => collapsed ? 'display: none;' : '' }
  %ul
    %li.date-time Monday December 27th, 2012 10:34am CST
    %li
      Status:
      %span.ms-red-text Online
      %li
        System Messages:
        %span.ms-red-text None at this time
      %li
        Reports:
        %span.ms-red-text 1234
      %li
        Metered Events:
        %span.ms-red-text 1,234,567
      %li
        Monitored Events:
        %span.ms-red-text 1,234,567

app/views/shared/widgets/_user_list.haml
- if users && users.length > 0
  - users.each do |u|
    %tr.user_info{'data-user_id' => u._id}
      %td.loading
      %td 
        = u.email
      %td 
      %td
      %td
- else
  %tr.user_info
    %td
    %td 
      (no results)
    %td 
    %td
    %td

app/views/shared/widgets/_user_management.html.haml
- if controller?(['dashboards'])
  %ul.machineshop-header
    %li= image_tag 'users_small.png'
    %li USER MANAGEMENT
    = render partial: 'shared/header_buttons', locals: {collapsed: collapsed}
  .machineshop-inner-container.user_management{ :style => collapsed ? 'display: none;' : '' }
    = form_tag('/widgets/retrieve_users', :method => :get, :id => 'user_search') do
      = text_field_tag :query, nil, :placeholder => "Search Users", :id => 'user-search-box'
      = submit_tag "Search", :class => "btn btn-mini"
    %ul.add-record#add-user
      %li= link_to image_tag('add-btn.png'), new_user_path
      %li= link_to "Add", new_user_path

    .table_container
      %table.table.table-striped#user-management-data
        %thead
          %tr
            %th Name
            %th Email
            %th Role
            %th Company
            %th Actions
        %tbody.paged_data
          %tr
            %td.loading
            %td
              Loading...
            %td
            %td
            %td

    .row-fluid.no-margin-left
      = render 'shared/pager'

- else
  .row-fluid
    %table.table.table-bordered.table-striped#user-management-data
      %thead
        %tr
          %th NAME
          %th EMAIL
          %th ROLE
          %th COMPANY
          %th ACTIONS
      %tbody.paged_data
        %tr
          %td.loading
          %td
            Loading...
          %td
          %td
          %td

  .row-fluid.no-margin-left
    = render 'shared/pager'

app/views/shared/widgets/_user_row.haml
%td
  = user_instance.full_name
%td
  %a{:href => "mailto:#{user_instance.email}"}
    = user_instance.email.truncate(24)
%td
  = user_instance.role.humanize
%td
  = user_instance.company_name.truncate(24)
%td
  %span
    = link_to("Edit", edit_user_path(user_instance._id))
  - if user_instance._id != current_user.id
    %span
    = link_to "/ Delete", user_instance,
    class: "delete",
    confirm: "Delete '#{user_instance.full_name}'?",
    method: :delete,
    remote: true
    :javascript
      $("a.delete").bind("ajax:success", function(evt, data, status, xhr) {
      $(this).closest("tr").fadeOut(500);
      });
      $("a.delete").bind("ajax:error", function(evt, xhr, status, error) {
      alert("We're sorry but something went wrong. The user was not deleted.")
      });